version: 1
defaults:
  cycle_budget_s: 5.0
  taut_timeout_s: 0.10
  max_candidates_per_cycle: 40

slices:
  slice_uplift_goal:      { cycle_budget_s: 5.0, taut_timeout_s: 0.10, max_candidates_per_cycle: 40 }
  slice_uplift_sparse:    { cycle_budget_s: 6.0, taut_timeout_s: 0.12, max_candidates_per_cycle: 40 }
  slice_uplift_tree:      { cycle_budget_s: 4.0, taut_timeout_s: 0.10, max_candidates_per_cycle: 30 }
  slice_uplift_dependency: { cycle_budget_s: 6.0, taut_timeout_s: 0.12, max_candidates_per_cycle: 40 }

